ADDITIONAL_UNSORTED :=	\
	strcmp.c			\
	strstr.c			\
	strnlen.c


ADDITIONAL_SOURCES := $(ADDITIONAL_UNSORTED)

ADDITIONAL_OBJECT_FILENAMES := $(addprefix ADDITIONAL_ft_,$(ADDITIONAL_SOURCES:.c=.o))

ADDITIONAL_OBJECTS := $(addprefix obj/,$(ADDITIONAL_OBJECT_FILENAMES))

ADDITIONAL_TESTER_OBJECTS := $(addprefix obj/test_,$(ADDITIONAL_OBJECT_FILENAMES))
